apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    replicas: 3                # Enables HA for ArgoCD Server
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

  repo:
    replicas: 2                # Enables HA for Repository Server
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

  controller:
    replicas: 3                # Enables HA for Application Controller
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

  redis:
    replicas: 3                # Redis HA enabled
    persistence:
      enabled: true            # Persistent storage only for Redis
      size: 5Gi

  rbac:
    policy: "local"            # RBAC management

  tls:
    selfSignedCertificate:
      enabled: false           # Disable auto TLS
