apiVersion: argoproj.io/v1alpha1  # Use the correct API version supported by your ArgoCD
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    replicas: 3               # Enable HA for ArgoCD Server
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

  repo:
    replicas: 2               # Enable HA for Repository Server
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

  applicationController:
    replicas: 3               # Enable HA for Application Controller
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

  redis:
    ha:
      enabled: true           # Enable Redis HA

  rbac:
    policy: "local"           # Enable RBAC
