apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: argocd-sc-retain
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  type: pd-ssd
  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-reposerver-storage-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: argocd-sc-retain
 